var APP_DATA = {
  "scenes": [
    {
      "id": "0-title_full",
      "name": "title_full",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        },
        {
          "tileSize": 512,
          "size": 1024
        }
      ],
      "faceSize": 1000,
      "initialViewParameters": {
        "yaw": 0.024166097335307057,
        "pitch": 0,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -0.34535553664127505,
          "pitch": 0.24568370077782653,
          "rotation": 0,
          "target": "1-hall_off-sala"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 0.30124089156398526,
          "pitch": 0.21934192666541286,
          "title": "<h1> &ensp; Credits </h1>",
          "text": "<h2> <p> Silent Hill 3 was developed by Team Silent and belongs to Konami Computer Entertainment Tokyo, 2003.</p> <br> <p> Renders, icons, texts and tour by Guilherme Hammel Cattaneo. </p> <br> <p> 3D Model rips by shprops4xnalara and trashboialex. </p> <br> <p> Information by the silenthill.fandom.com and silenthillmemories.net </p> <br> <p> 360 interactive web application generated by the Marzipano Tool. </p> <br> <img src='img/logo.png' height=35px> <br> <p> Special thanks to Saturnoia for the help! </p> <br> v.1.2 - 02/12/2021 </h2>"
        },
        {
          "yaw": -0.0515710812816117,
          "pitch": 0.2621054210469502,
          "title": "<h1> &ensp; Plot <h1>",
          "text": "<h2><p>In Silent Hill 1, Harry Mason has his adopted daughter Cheryl captured by a mysterious cult (the Order) while visiting the town of Silent Hill. Harry spends the entire game trying to find his daughter, the one considered by the cult to be the incarnation of Alessa Gillespie, a girl with the ability to give birth to God.</p><br><p>After rescuing his daughter, Harry was very afraid that his daughter could be kidnapped by the Order again, thus changing Cheryl's identity to Heather Mason.</p><br><p>This tour takes place in Silent hill 3, in the Masons' apartment: a direct sequel to the first game. Heather returns home after being chased by creatures and finds her father, Harry Mason, dead on the couch. He was killed by a monster of Claudia Wolf, leader of the Order who wants to force Heather Mason again to give birth to God. <br> <br> <img src='img/heather.png' class='center'></h2>"
        }
      ]
    },
    {
      "id": "1-hall_off-sala",
      "name": "hall_off (sala)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -0.09934951126737346,
        "pitch": 0.02940767117888754,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -0.4448341979556236,
          "pitch": 0.2741961389360199,
          "rotation": 0,
          "target": "8-sala_off-heather"
        },
        {
          "yaw": 0.2698675002219968,
          "pitch": 0.31414308279160785,
          "rotation": 0,
          "target": "22-cozinha_off"
        },
        {
          "yaw": -2.4585584802435143,
          "pitch": 0.29616331618701963,
          "rotation": 0,
          "target": "36-harry_room_off-cama"
        },
        {
          "yaw": -1.7370969271653252,
          "pitch": 0.4221664758560273,
          "rotation": 0,
          "target": "32-jantar_off"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "2-hall_on-sala",
      "name": "hall_on (sala)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -0.07384085296899379,
        "pitch": 0.0018379794486804713,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -2.4623993495792966,
          "pitch": 0.30138294983414227,
          "rotation": 0,
          "target": "37-harry_room_on-cama"
        },
        {
          "yaw": -1.7267636718419261,
          "pitch": 0.3760384293534571,
          "rotation": 0,
          "target": "33-jantar_on"
        },
        {
          "yaw": -0.4397223817017295,
          "pitch": 0.2680957723174995,
          "rotation": 0,
          "target": "9-sala_on-heather"
        },
        {
          "yaw": 0.2677184401254351,
          "pitch": 0.31711071295029214,
          "rotation": 0,
          "target": "31-cozinha_on-geladeira"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "3-hall_off-parede",
      "name": "hall_off (parede)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.598832158670822,
        "pitch": 0.050922842372280286,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.2869400982817538,
          "pitch": 0.33187761957115214,
          "rotation": 0,
          "target": "22-cozinha_off"
        },
        {
          "yaw": -0.4546056691444793,
          "pitch": 0.2655981442153781,
          "rotation": 0,
          "target": "8-sala_off-heather"
        },
        {
          "yaw": -1.7517810692953937,
          "pitch": 0.4242942222222883,
          "rotation": 0,
          "target": "32-jantar_off"
        },
        {
          "yaw": -2.4552837246705455,
          "pitch": 0.31113206189861664,
          "rotation": 0,
          "target": "36-harry_room_off-cama"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "4-hall_on-parede",
      "name": "hall_on (parede)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.5503979290199972,
        "pitch": 0.09412224822439796,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -2.458306487717472,
          "pitch": 0.3071242897298916,
          "rotation": 0,
          "target": "37-harry_room_on-cama"
        },
        {
          "yaw": -1.739384616379505,
          "pitch": 0.4051128459450286,
          "rotation": 0,
          "target": "33-jantar_on"
        },
        {
          "yaw": -0.4422368483774779,
          "pitch": 0.27713841229669,
          "rotation": 0,
          "target": "9-sala_on-heather"
        },
        {
          "yaw": 0.2889820919130379,
          "pitch": 0.32243867610473487,
          "rotation": 0,
          "target": "31-cozinha_on-geladeira"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "5-hall_off-exit-harry",
      "name": "hall_off (exit-harry)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -3.1300377348637145,
        "pitch": 0.1458424461929244,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.2974076922073863,
          "pitch": 0.3241095003476637,
          "rotation": 0,
          "target": "22-cozinha_off"
        },
        {
          "yaw": -0.4465865766146102,
          "pitch": 0.26989926848903245,
          "rotation": 0,
          "target": "8-sala_off-heather"
        },
        {
          "yaw": -1.7687970334548755,
          "pitch": 0.4304622110554366,
          "rotation": 0,
          "target": "32-jantar_off"
        },
        {
          "yaw": -2.4587539486406307,
          "pitch": 0.3066392608812514,
          "rotation": 0,
          "target": "36-harry_room_off-cama"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "6-hall_on-exit-harry",
      "name": "hall_on (exit-harry)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -3.1152889925740244,
        "pitch": 0.1415244175484318,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.27393987118573904,
          "pitch": 0.3069511283727451,
          "rotation": 0,
          "target": "31-cozinha_on-geladeira"
        },
        {
          "yaw": -0.44202327107611517,
          "pitch": 0.26641974155320014,
          "rotation": 0,
          "target": "9-sala_on-heather"
        },
        {
          "yaw": -1.7338947826805722,
          "pitch": 0.3976496129006577,
          "rotation": 0,
          "target": "33-jantar_on"
        },
        {
          "yaw": -2.4726329405813825,
          "pitch": 0.2977498404768646,
          "rotation": 0,
          "target": "37-harry_room_on-cama"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "7-hall_on2",
      "name": "hall_on2",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -3.0927722549326155,
        "pitch": 0.13901808193658383,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -2.468806585244085,
          "pitch": 0.2990033073972693,
          "rotation": 0,
          "target": "37-harry_room_on-cama"
        },
        {
          "yaw": -1.741387090999984,
          "pitch": 0.42401705379345245,
          "rotation": 0,
          "target": "33-jantar_on"
        },
        {
          "yaw": -0.44403459662016687,
          "pitch": 0.2592469766835883,
          "rotation": 0,
          "target": "9-sala_on-heather"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "8-sala_off-heather",
      "name": "sala_off (heather)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -0.33832536269427926,
        "pitch": 0.05146342456305675,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.1555256487170773,
          "pitch": 0.2861895174649529,
          "rotation": 0,
          "target": "14-heather_room_door_off-taser"
        },
        {
          "yaw": -1.8791685230441182,
          "pitch": 0.3339794581551949,
          "rotation": 0,
          "target": "34-varanda_off"
        },
        {
          "yaw": 2.3876512723741907,
          "pitch": 0.30274589285047604,
          "rotation": 0,
          "target": "5-hall_off-exit-harry"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 2.963891904852817,
          "pitch": 0.3093752623259203,
          "title": "<h1> &ensp; Armchair </h1>",
          "text": "<img src='img/armchair.jpg'  class='center'> <br> <h2> <p> Harry's body, mutilated by the missionary of the Order, is found here by Heather. He is framed in such a way that his face is never actually shown. <p> <br> <p> But Harry has a face. The face of the protagonist of Silent Hill 2, James Sunderland, only visible by extracting his 3D model or modding the game's camera. </p> <br> <img src='img/harry.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "9-sala_on-heather",
      "name": "sala_on (heather)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -0.3571212161773101,
        "pitch": 0.07168119849854193,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 2.3910923285689893,
          "pitch": 0.2978820606234329,
          "rotation": 0,
          "target": "6-hall_on-exit-harry"
        },
        {
          "yaw": 0.14236077390335922,
          "pitch": 0.2833326220446004,
          "rotation": 0,
          "target": "15-heather_room_door_on-taser"
        },
        {
          "yaw": -1.8684175884267997,
          "pitch": 0.3334914809687284,
          "rotation": 0,
          "target": "35-varanda_on"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 2.939482343434519,
          "pitch": 0.3009407797432786,
          "title": "<h1> &ensp; Armchair </h1>",
          "text": "<img src='img/armchair.jpg'  class='center'> <br> <h2> <p> Harry's body, mutilated by the missionary of the Order, is found here by Heather. He is framed in such a way that his face is never actually shown. <p> <br> <p> But Harry has a face. The face of the protagonist of Silent Hill 2, James Sunderland, only visible by extracting his 3D model or modding the game's camera. </p> <br> <img src='img/harry.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "10-sala_off-hall",
      "name": "sala_off (hall)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 3.063846168728217,
        "pitch": 0.1350079449576569,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -1.8658747109103668,
          "pitch": 0.3307429445492005,
          "rotation": 0,
          "target": "34-varanda_off"
        },
        {
          "yaw": 0.14598549425658724,
          "pitch": 0.292141950020099,
          "rotation": 0,
          "target": "14-heather_room_door_off-taser"
        },
        {
          "yaw": 2.394065431856281,
          "pitch": 0.3066966638248587,
          "rotation": 0,
          "target": "5-hall_off-exit-harry"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 2.9335579305597044,
          "pitch": 0.29202513691871346,
          "title": "<h1> &ensp; Armchair </h1>",
          "text": "<img src='img/armchair.jpg'  class='center'> <br> <h2> <p> Harry's body, mutilated by the missionary of the Order, is found here by Heather. He is framed in such a way that his face is never actually shown. <p> <br> <p> But Harry has a face. The face of the protagonist of Silent Hill 2, James Sunderland, only visible by extracting his 3D model or modding the game's camera. </p> <br> <img src='img/harry.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "11-sala_on-hall",
      "name": "sala_on (hall)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 2.9773468058396926,
        "pitch": 0.1515125798293191,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 2.3912923067356555,
          "pitch": 0.30936244590329487,
          "rotation": 0,
          "target": "6-hall_on-exit-harry"
        },
        {
          "yaw": -1.8711776765131827,
          "pitch": 0.3450576435203647,
          "rotation": 0,
          "target": "35-varanda_on"
        },
        {
          "yaw": 0.15039521613420526,
          "pitch": 0.276297855154521,
          "rotation": 0,
          "target": "15-heather_room_door_on-taser"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 2.9358331825336776,
          "pitch": 0.321669428019014,
          "title": "<h1> &ensp; Armchair </h1>",
          "text": "<img src='img/armchair.jpg'  class='center'> <br> <h2> <p> Harry's body, mutilated by the missionary of the Order, is found here by Heather. He is framed in such a way that his face is never actually shown. <p> <br> <p> But Harry has a face. The face of the protagonist of Silent Hill 2, James Sunderland, only visible by extracting his 3D model or modding the game's camera. </p> <br> <img src='img/harry.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "12-sala_off-parede",
      "name": "sala_off (parede)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.357329133666358,
        "pitch": 0.031245650627591104,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.1397972147150277,
          "pitch": 0.2917012985138836,
          "rotation": 0,
          "target": "14-heather_room_door_off-taser"
        },
        {
          "yaw": -1.8780448359182493,
          "pitch": 0.3239538704568865,
          "rotation": 0,
          "target": "34-varanda_off"
        },
        {
          "yaw": 2.371983234948262,
          "pitch": 0.31666652993435207,
          "rotation": 0,
          "target": "5-hall_off-exit-harry"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 2.972107444448848,
          "pitch": 0.29284008018434804,
          "title": "<h1> &ensp; Armchair </h1>",
          "text": "<img src='img/armchair.jpg'  class='center'> <br> <h2> <p> Harry's body, mutilated by the missionary of the Order, is found here by Heather. He is framed in such a way that his face is never actually shown. <p> <br> <p> But Harry has a face. The face of the protagonist of Silent Hill 2, James Sunderland, only visible by extracting his 3D model or modding the game's camera. </p> <br> <img src='img/harry.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "13-sala_on-parede",
      "name": "sala_on (parede)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.350608396724228,
        "pitch": -0.005503079184794757,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.1629301771994296,
          "pitch": 0.2938622963173465,
          "rotation": 0,
          "target": "15-heather_room_door_on-taser"
        },
        {
          "yaw": 2.3940905233629897,
          "pitch": 0.31319145374154544,
          "rotation": 0,
          "target": "6-hall_on-exit-harry"
        },
        {
          "yaw": -1.8801554839659573,
          "pitch": 0.3427048058035833,
          "rotation": 0,
          "target": "35-varanda_on"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 2.9644465603333865,
          "pitch": 0.28625109283918526,
          "title": "<h1> &ensp; Armchair </h1>",
          "text": "<img src='img/armchair.jpg'  class='center'> <br> <h2> <p> Harry's body, mutilated by the missionary of the Order, is found here by Heather. He is framed in such a way that his face is never actually shown. <p> <br> <p> But Harry has a face. The face of the protagonist of Silent Hill 2, James Sunderland, only visible by extracting his 3D model or modding the game's camera. </p> <br> <img src='img/harry.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "14-heather_room_door_off-taser",
      "name": "Heather_room_door_off (taser)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -2.2636925488070325,
        "pitch": 0.1689637962281374,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.3386255780142058,
          "pitch": 0.28537321510185265,
          "rotation": 0,
          "target": "10-sala_off-hall"
        },
        {
          "yaw": 1.3920444741892535,
          "pitch": 0.48479608660339757,
          "rotation": 0,
          "target": "16-heather_room_bed_off"
        },
        {
          "yaw": -1.4178785836657433,
          "pitch": 0.5438014916549978,
          "rotation": 0,
          "target": "18-heather_bathroom_off"
        }
      ],
      "infoHotspots": [
        {
          "yaw": -2.4521541997562135,
          "pitch": 0.18704494623962908,
          "title": "<h1> &ensp; Taser </h1>",
          "text": "<h2> <img src='img/taser.jpg' class='center'> <br> <p> Unlike other weapons, the Taser already belongs to Heather. Upon examining it, she mentions that it was a gift from her ‘worrywart dad’ and it turns out to be a reminder of real horrors like the fear of being abused. The theme of ‘sexual abuse’ can be also seen in the Order's intentions to force Heather to give birth to God. </p> </h2>"
        },
        {
          "yaw": 2.7253727276670086,
          "pitch": 0.18708259425834584,
          "title": "<h1> &ensp; Poster </h1>",
          "text": "<h2> <img src='img/un_notte.jpg' class='center'> <br> <p> The only words I can make out clearly are ‘Un Notte’. On examination, Heather notes that the hero of the movie has a line that goes: ‘Morning always comes, it's corny but it's true. But if your eyes are closed, it always feels like night.’ </p> <br> <p> There is an error in the poster, where the title must be ‘Un Notte’ to be translated from Italian as ‘a night’. </p> <br> <p> On the poster is also possible to see Toluca Lake, the one that surrounds the forest of Silent Hill. </p> <br> <img src='img/un_notte2.jpg' class='center'> <br> <p> Another photo of this lake can also be seen on Heather's wall, almost as if Silent Hill was calling out to her in her subconscious. </p> <br> <img src='img/lake.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "15-heather_room_door_on-taser",
      "name": "Heather_room_door_on (taser)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -2.2750731610546104,
        "pitch": 0.14146612013132653,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -1.3890915988110777,
          "pitch": 0.5127577626697075,
          "rotation": 0,
          "target": "19-heather_bathroom_on"
        },
        {
          "yaw": 1.4208857492928093,
          "pitch": 0.47108380364474023,
          "rotation": 0,
          "target": "17-heather_room_bed_on"
        },
        {
          "yaw": 0.3422679419569139,
          "pitch": 0.28957640932652673,
          "rotation": 0,
          "target": "11-sala_on-hall"
        }
      ],
      "infoHotspots": [
        {
          "yaw": -2.4492449581858047,
          "pitch": 0.17872899569359113,
          "title": "<h1> &ensp; Taser </h1>",
          "text": "<h2> <img src='img/taser.jpg' class='center'> <br> <p> Unlike other weapons, the Taser already belongs to Heather. Upon examining it, she mentions that it was a gift from her ‘worrywart dad’ and it turns out to be a reminder of real horrors like the fear of being abused. The theme of ‘sexual abuse’ can be also seen in the Order's intentions to force Heather to give birth to God. </p> </h2>"
        },
        {
          "yaw": 2.7296297642497827,
          "pitch": 0.19021835944595367,
          "title": "<h1> &ensp; Poster </h1>",
          "text": "<h2> <img src='img/un_notte.jpg' class='center'> <br> <p> The only words I can make out clearly are ‘Un Notte’. On examination, Heather notes that the hero of the movie has a line that goes: ‘Morning always comes, it's corny but it's true. But if your eyes are closed, it always feels like night.’ </p> <br> <p> There is an error in the poster, where the title must be ‘Un Notte’ to be translated from Italian as ‘a night’. </p> <br> <p> On the poster is also possible to see Toluca Lake, the one that surrounds the forest of Silent Hill. </p> <br> <img src='img/un_notte2.jpg' class='center'> <br> <p> Another photo of this lake can also be seen on Heather's wall, almost as if Silent Hill was calling out to her in her subconscious. </p> <br> <img src='img/lake.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "16-heather_room_bed_off",
      "name": "Heather_room_bed_off",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 0.02148097540916183,
        "pitch": 0.19666380100883885,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 3.112956529905759,
          "pitch": 0.4838722357804208,
          "rotation": 0,
          "target": "14-heather_room_door_off-taser"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 2.021488514568629,
          "pitch": -0.19316299072636767,
          "title": "<h1> &ensp;  Painting 4 </h1>",
          "text": "<h2> <img src='img/pintura4-big' class='center'> <br> <p> A painting of a creature looking to the crescent moon. </p> <br> <p> Enlarged with AI. </p> </h2>"
        },
        {
          "yaw": 1.3942606783086706,
          "pitch": -0.29042742208563865,
          "title": "<h1> &ensp;  Painting 2 </h1>",
          "text": "<h2> <img src='img/pintura2-big.jpg' class='center'> <br> <p> A very dark painting.</p> </h2>"
        },
        {
          "yaw": 1.5816590522038432,
          "pitch": -0.17368647719842656,
          "title": "<h1> &ensp;  Painting 3 </h1>",
          "text": "<h2> <img src='img/pintura3-big.jpg' class='center'> <br> <p> A painting of a face with exaggerated proportions. </p> </h2>"
        },
        {
          "yaw": 1.1331680556945898,
          "pitch": -0.15188380095449716,
          "title": "<h1> &ensp;  Painting 1 </h1>",
          "text": "<h2> <img src='img/pintura1-big.jpg' class='center'> <br> <p> A painting of a woman.</p> <br> <p> Hm… </p> <br> <p> This one looks like the European cover for <br> Silent Hill 3.</p> <br><img src='img/cover.jpg' class='center'></h2>"
        }
      ]
    },
    {
      "id": "17-heather_room_bed_on",
      "name": "Heather_room_bed_on",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 0.010740487704580914,
        "pitch": 0.15622825313786137,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 3.1049164355574126,
          "pitch": 0.485088552068472,
          "rotation": 0,
          "target": "15-heather_room_door_on-taser"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 1.1274901360083316,
          "pitch": -0.15160496571763638,
          "title": "<h1> &ensp; Painting 1 </h1>",
          "text": "<h2> <img src='img/pintura1-big.jpg' class='center'> <br> <p> A painting of a woman.</p> <br> <p> Hm… </p> <br> <p> This one looks like the European cover for <br> Silent Hill 3.</p> <br><img src='img/cover.jpg' class='center'></h2>"
        },
        {
          "yaw": 1.3987013555986891,
          "pitch": -0.2815702233861721,
          "title": "<h1> &ensp; Painting 2 </h1>",
          "text": "<h2> <img src='img/pintura2-big.jpg' class='center'> <br> <p> A very dark painting.</p> </h2>"
        },
        {
          "yaw": 1.5883595125716727,
          "pitch": -0.15799111818890665,
          "title": "<h1> &ensp; Painting 3 </h1>",
          "text": "<h2> <img src='img/pintura3-big.jpg' class='center'> <br> <p> A painting of a face with exaggerated proportions. </p> </h2>"
        },
        {
          "yaw": 2.019985820039497,
          "pitch": -0.19417149179985316,
          "title": "<h1> &ensp; Painting 4 </h1>",
          "text": "<h2> <img src='img/pintura4-big.jpg' class='center'> <br> <p> A painting of a creature looking to the crescent moon. </p> </h2>"
        }
      ]
    },
    {
      "id": "18-heather_bathroom_off",
      "name": "Heather_bathroom_off",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -3.06531907534513,
        "pitch": 0.16413079999075464,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.2298549751760266,
          "pitch": 0.5153940074674832,
          "rotation": 0,
          "target": "20-heather_room_door_off-cama"
        }
      ],
      "infoHotspots": [
        {
          "yaw": -0.4657585927113388,
          "pitch": 0.20755077096108465,
          "title": "<h1> &ensp; Light switch </h1> ",
          "text": "<h2> <p> This bathroom has no light switch. </p> <br> <p> Strange. </p> <h2>"
        }
      ]
    },
    {
      "id": "19-heather_bathroom_on",
      "name": "Heather_bathroom_on",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -3.0642293584062656,
        "pitch": 0.16932495575753492,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.1715224113270395,
          "pitch": 0.5138655558483407,
          "rotation": 0,
          "target": "21-heather_room_door_on"
        }
      ],
      "infoHotspots": [
        {
          "yaw": -0.4033850484364354,
          "pitch": 0.13504992772637614,
          "title": "<h1> &ensp; Light switch </h1>",
          "text": "<h2> <p> This bathroom has no light switch. </p> <br> <p> Strange. </p> <h2>"
        }
      ]
    },
    {
      "id": "20-heather_room_door_off-cama",
      "name": "Heather_room_door_off (cama)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.5840828798843996,
        "pitch": 0.09041895242234688,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.3359311534196898,
          "pitch": 0.27576128303389247,
          "rotation": 0,
          "target": "10-sala_off-hall"
        },
        {
          "yaw": 1.3898351610041484,
          "pitch": 0.4180076086679545,
          "rotation": 0,
          "target": "16-heather_room_bed_off"
        },
        {
          "yaw": -1.390517234077718,
          "pitch": 0.558739616551378,
          "rotation": 0,
          "target": "18-heather_bathroom_off"
        }
      ],
      "infoHotspots": [
        {
          "yaw": -2.4313742441855,
          "pitch": 0.18299715537219186,
          "title": "<h1> &ensp; Taser </h1>",
          "text": "<h2> <img src='img/taser.jpg' class='center'> <br> <p> Unlike other weapons, the Taser already belongs to Heather. Upon examining it, she mentions that it was a gift from her ‘worrywart dad’ and it turns out to be a reminder of real horrors like the fear of being abused. The theme of ‘sexual abuse’ can be also seen in the Order's intentions to force Heather to give birth to God. </p> </h2>"
        },
        {
          "yaw": 2.7321725722576993,
          "pitch": 0.18709836828949022,
          "title": "<h1> &ensp; Poster </h1>",
          "text": "<h2> <img src='img/un_notte.jpg' class='center'> <br> <p> The only words I can make out clearly are ‘Un Notte’. On examination, Heather notes that the hero of the movie has a line that goes: ‘Morning always comes, it's corny but it's true. But if your eyes are closed, it always feels like night.’ </p> <br> <p> There is an error in the poster, where the title must be ‘Un Notte’ to be translated from Italian as ‘a night’. </p> <br> <p> On the poster is also possible to see Toluca Lake, the one that surrounds the forest of Silent Hill. </p> <br> <img src='img/un_notte2.jpg' class='center'> <br> <p> Another photo of this lake can also be seen on Heather's wall, almost as if Silent Hill was calling out to her in her subconscious. </p> <br> <img src='img/lake.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "21-heather_room_door_on",
      "name": "Heather_room_door_on",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.5748306306693927,
        "pitch": 0.14253061287955404,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 1.4270972022991781,
          "pitch": 0.432620146577845,
          "rotation": 0,
          "target": "17-heather_room_bed_on"
        },
        {
          "yaw": -1.418963781443022,
          "pitch": 0.529584851002662,
          "rotation": 0,
          "target": "19-heather_bathroom_on"
        },
        {
          "yaw": 0.3396035221571374,
          "pitch": 0.29495590135826255,
          "rotation": 0,
          "target": "11-sala_on-hall"
        }
      ],
      "infoHotspots": [
        {
          "yaw": -2.406521193287661,
          "pitch": 0.20705144560274924,
          "title": "<h1> &ensp; Taser </h1>",
          "text": "<h2> <img src='img/taser.jpg' class='center'> <br> <p> Unlike other weapons, the Taser already belongs to Heather. Upon examining it, she mentions that it was a gift from her ‘worrywart dad’ and it turns out to be a reminder of real horrors like the fear of being abused. The theme of ‘sexual abuse’ can be also seen in the Order's intentions to force Heather to give birth to God. </p> </h2>"
        },
        {
          "yaw": 2.749737706717341,
          "pitch": 0.1896582272935845,
          "title": "<h1> &ensp; Poster </h1>",
          "text": "<h2> <img src='img/un_notte.jpg' class='center'> <br> <p> The only words I can make out clearly are ‘Un Notte’. On examination, Heather notes that the hero of the movie has a line that goes: ‘Morning always comes, it's corny but it's true. But if your eyes are closed, it always feels like night.’ </p> <br> <p> There is an error in the poster, where the title must be ‘Un Notte’ to be translated from Italian as ‘a night’. </p> <br> <p> On the poster is also possible to see Toluca Lake, the one that surrounds the forest of Silent Hill. </p> <br> <img src='img/un_notte2.jpg' class='center'> <br> <p> Another photo of this lake can also be seen on Heather's wall, almost as if Silent Hill was calling out to her in her subconscious. </p> <br> <img src='img/lake.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "22-cozinha_off",
      "name": "cozinha_off",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 0,
        "pitch": 0,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "23-cozinha_on-1"
        },
        {
          "yaw": -1.309867579000688,
          "pitch": 0.34956643079437555,
          "rotation": 0,
          "target": "5-hall_off-exit-harry"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "23-cozinha_on-1",
      "name": "cozinha_on (1)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "pitch": 0,
        "yaw": 0,
        "fov": 1.5707963267948966
      },
      "linkHotspots": [
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "24-cozinha_off-1"
        },
        {
          "yaw": -1.2934227698708742,
          "pitch": 0.34220187752171327,
          "rotation": 0,
          "target": "6-hall_on-exit-harry"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 1.6530445306548298,
          "pitch": -0.043104746094529744,
          "title": "<h1> &ensp; Food </h1>",
          "text": "<h2> <p> ‘Who could eat something in a situation like this?’ </p> <br> <p id='p1'> - Heather. </p> </h2>"
        }
      ]
    },
    {
      "id": "24-cozinha_off-1",
      "name": "cozinha_off (1)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "pitch": 0,
        "yaw": 0,
        "fov": 1.5707963267948966
      },
      "linkHotspots": [
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "25-cozinha_on-2"
        },
        {
          "yaw": -1.236893904819663,
          "pitch": 0.3345384782175582,
          "rotation": 0,
          "target": "5-hall_off-exit-harry"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "25-cozinha_on-2",
      "name": "cozinha_on (2)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "pitch": 0,
        "yaw": 0,
        "fov": 1.5707963267948966
      },
      "linkHotspots": [
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "26-cozinha_off-2"
        },
        {
          "yaw": -1.2371914404057556,
          "pitch": 0.34794105892486016,
          "rotation": 0,
          "target": "6-hall_on-exit-harry"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 1.6544383342117328,
          "pitch": -0.04501812227936597,
          "title": "<h1> &ensp; Food </h1> ",
          "text": "<h2> <p> ‘Who could eat something in a situation like this?’ </p> <br> <p id='p1'> - Heather. </p> </h2>"
        }
      ]
    },
    {
      "id": "26-cozinha_off-2",
      "name": "cozinha_off (2)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "pitch": 0,
        "yaw": 0,
        "fov": 1.5707963267948966
      },
      "linkHotspots": [
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "27-cozinha_on-3"
        },
        {
          "yaw": -1.2430303524674926,
          "pitch": 0.32044800250733374,
          "rotation": 0,
          "target": "5-hall_off-exit-harry"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "27-cozinha_on-3",
      "name": "cozinha_on (3)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "pitch": 0,
        "yaw": 0,
        "fov": 1.5707963267948966
      },
      "linkHotspots": [
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "28-cozinha_off-3"
        },
        {
          "yaw": -1.2149406037398158,
          "pitch": 0.33183693803722747,
          "rotation": 0,
          "target": "7-hall_on2"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 1.6573217688775053,
          "pitch": -0.04720276930963152,
          "title": "<h1> &ensp; Food </h1> ",
          "text": "<h2> <p> ‘Who could eat something in a situation like this?’ </p> <br> <p id='p1'> - Heather. </p> </h2>"
        }
      ]
    },
    {
      "id": "28-cozinha_off-3",
      "name": "cozinha_off (3)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "pitch": 0,
        "yaw": 0,
        "fov": 1.5707963267948966
      },
      "linkHotspots": [
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "42-vazio_cozinha"
        },
        {
          "yaw": -1.2057870872488028,
          "pitch": 0.3384075271917162,
          "rotation": 0,
          "target": "5-hall_off-exit-harry"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "29-cozinha_on-4",
      "name": "cozinha_on (4)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "pitch": 0,
        "yaw": 0,
        "fov": 1.5707963267948966
      },
      "linkHotspots": [
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "30-cozinha_off-4"
        },
        {
          "yaw": -1.2343318942627306,
          "pitch": 0.3339134754992976,
          "rotation": 0,
          "target": "6-hall_on-exit-harry"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 1.6519494766177845,
          "pitch": -0.04025080381812174,
          "title": "<h1> &ensp; Food </h1> ",
          "text": "<h2> <p> ‘Who could eat something in a situation like this?’ </p> <br> <p id='p1'> - Heather. </p> </h2>"
        }
      ]
    },
    {
      "id": "30-cozinha_off-4",
      "name": "cozinha_off (4)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "pitch": 0,
        "yaw": 0,
        "fov": 1.5707963267948966
      },
      "linkHotspots": [
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "29-cozinha_on-4"
        },
        {
          "yaw": -1.2518160421797422,
          "pitch": 0.3529462599984754,
          "rotation": 0,
          "target": "5-hall_off-exit-harry"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "31-cozinha_on-geladeira",
      "name": "cozinha_on (geladeira)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.8815206200098142,
        "pitch": 0.17828616171370726,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "30-cozinha_off-4"
        },
        {
          "yaw": -1.2624041023770811,
          "pitch": 0.35857963559768713,
          "rotation": 0,
          "target": "6-hall_on-exit-harry"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 1.6565182060707624,
          "pitch": -0.040738556814492455,
          "title": "<h1> &ensp; Butter Cake</h1>",
          "text": "<h2> <img src='img/butter.jpg' class='center'> <br> <p> 3 huge boxes of pre-made butter cake. </p> <br> <p id='p1'> wtf Harry.</p> </h2>"
        }
      ]
    },
    {
      "id": "32-jantar_off",
      "name": "jantar_off",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -1.5439374806300954,
        "pitch": 0.15489758540257625,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 1.4040750591804638,
          "pitch": 0.39441678863217433,
          "rotation": 0,
          "target": "3-hall_off-parede"
        }
      ],
      "infoHotspots": [
        {
          "yaw": -2.6498699003470865,
          "pitch": 0.1731754615052079,
          "title": "<h1> &ensp; Family </h1>",
          "text": "<h2> <img src='img/family.jpg' class='center'> <br> <p> A handmade art-piece of Jodie Mason, Harry's wife, holding hands with his two adopted daughters. Which is presumably a tribute to his lost wife and child. </p> <br> <p> ‘A painting of Jodie holding Cheryl's and Heather's hands’ </p> <br> <p> At this point in the game, Heather doesn't know that she was Cheryl. </p> </h2>"
        }
      ]
    },
    {
      "id": "33-jantar_on",
      "name": "jantar_on",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -1.576436298818825,
        "pitch": 0.16207636956549365,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 1.3976730313289032,
          "pitch": 0.4044519156276003,
          "rotation": 0,
          "target": "4-hall_on-parede"
        }
      ],
      "infoHotspots": [
        {
          "yaw": -2.6938344315970504,
          "pitch": 0.18729485466234763,
          "title": "<h1> &ensp; Family </h1>",
          "text": "<h2> <img src='img/family.jpg' class='center'> <br> <p> A handmade art-piece of Jodie Mason, Harry's wife, holding hands with his two adopted daughters. Which is presumably a tribute to his lost wife and child. </p> <br> <p> ‘A painting of Jodie holding Cheryl's and Heather's hands’ </p> <br> <p> At this point in the game, Heather doesn't know that she was Cheryl. </p> </h2>"
        }
      ]
    },
    {
      "id": "34-varanda_off",
      "name": "varanda_off",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -3.132905494416967,
        "pitch": 0.4325738690689285,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -0.14461499859952376,
          "pitch": 0.29881171873614853,
          "rotation": 0,
          "target": "12-sala_off-parede"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 1.5289386292917033,
          "pitch": -0.618477812214655,
          "title": "<h1> &ensp; The Monster </h1>",
          "text": "<h2>Escaped to the roof.</h2>"
        }
      ]
    },
    {
      "id": "35-varanda_on",
      "name": "varanda_on",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 3.1331931068106798,
        "pitch": 0.45466615152549394,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -0.1543842546365095,
          "pitch": 0.304943098245106,
          "rotation": 0,
          "target": "13-sala_on-parede"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 1.5225224980624397,
          "pitch": -0.6496107983310466,
          "title": "<h1> &ensp; The Monster </h1> ",
          "text": "<h2>Escaped to the roof.</h2>"
        }
      ]
    },
    {
      "id": "36-harry_room_off-cama",
      "name": "Harry_room_off (cama)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.9729543607334428,
        "pitch": 0.37745414314272807,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -0.9391762290036478,
          "pitch": 0.2809383624023525,
          "rotation": 0,
          "target": "1-hall_off-sala"
        },
        {
          "yaw": 0.43304960093749223,
          "pitch": 0.33785045495780786,
          "rotation": 0,
          "target": "38-harry_bathroom_off"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 1.3053165352852876,
          "pitch": -0.1143100628316116,
          "title": "<h1> &ensp; Photo </h1>",
          "text": "<h2> <img src='img/photo.jpg' class='center'><br><p> A photo of Harry and Heather. The image of Harry is just a render of him from the first game composed into one of Heather. Because of this, not only does Harry not appear to have aged in the photo, but the two of them are also the same height. It was most likely removed from the final version because of these inaccuracies. </p><br><p> The text attached to the picture in the game's source code reads: </p><br><p>  ‘It's of dad and me at Christmas. Looking at this makes me want to try even harder. I have to... I can't lose. They killed my dad and they have to pay for it.’ </p> <h2>"
        },
        {
          "yaw": 2.0554248760076446,
          "pitch": 0.21522931512417642,
          "title": "<h1> &ensp; Body </h1>",
          "text": "<h2> <p>'What else can I do? There is no one here to give him a decent burial.' </p> <br> <p id='p1'> - Heather. </p> </h2>"
        }
      ]
    },
    {
      "id": "37-harry_room_on-cama",
      "name": "Harry_room_on (cama)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.9609287478289197,
        "pitch": 0.3799211636861237,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.42445753376834716,
          "pitch": 0.31132108285278015,
          "rotation": 0,
          "target": "39-harry_bathroom_on"
        },
        {
          "yaw": -0.9087512536801263,
          "pitch": 0.2846384051882289,
          "rotation": 0,
          "target": "2-hall_on-sala"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 2.050591188250791,
          "pitch": 0.22052013799503278,
          "title": "<h1> &ensp; Body </h1>",
          "text": "<h2> <p>'What else can I do? There is no one here to give him a decent burial.' </p> <br> <p id='p1'> - Heather. </p> </h2>"
        },
        {
          "yaw": 1.3102031784939001,
          "pitch": -0.10113714895573445,
          "title": "<h1> &ensp; Photo </h1>",
          "text": "<h2> <img src='img/photo.jpg' class='center'><br><p> A photo of Harry and Heather. The image of Harry is just a render of him from the first game composed into one of Heather. Because of this, not only does Harry not appear to have aged in the photo, but the two of them are also the same height. It was most likely removed from the final version because of these inaccuracies. </p><br><p> The text attached to the picture in the game's source code reads: </p><br><p>  ‘It's of dad and me at Christmas. Looking at this makes me want to try even harder. I have to... I can't lose. They killed my dad and they have to pay for it.’ </p> <h2>"
        }
      ]
    },
    {
      "id": "38-harry_bathroom_off",
      "name": "Harry_bathroom_off",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.8397050449374364,
        "pitch": 0.1865196646433649,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -1.1195097723283585,
          "pitch": 0.38533324789209367,
          "rotation": 0,
          "target": "40-harry_room_off-tv"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 0.5251172502238912,
          "pitch": -0.19924120656410516,
          "title": "<h1> &ensp; Wall </h1>",
          "text": "<h2> <p> The different rooms are not meant to be connected directly. The hall, for example, clips through Harry's bathroom. </p> <br> <img src='img/wall.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "39-harry_bathroom_on",
      "name": "Harry_bathroom_on",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.6804585365904536,
        "pitch": 0.14936561634801748,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -1.1397766158697031,
          "pitch": 0.3623219294982363,
          "rotation": 0,
          "target": "41-harry_room_on-tv"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 0.4408321311757035,
          "pitch": -0.25945038386672437,
          "title": "<h1> &ensp; Wall </h1>",
          "text": "<h2> <p> The different rooms are not meant to be connected directly. The hall, for example, clips through Harry's bathroom. </p> <br> <img src='img/wall.jpg' class='center'> </h2>"
        }
      ]
    },
    {
      "id": "40-harry_room_off-tv",
      "name": "Harry_room_off (tv)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -2.4335947590971436,
        "pitch": 0.23517362198421132,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.41805870143568313,
          "pitch": 0.32604974656183217,
          "rotation": 0,
          "target": "38-harry_bathroom_off"
        },
        {
          "yaw": -0.9055200045714908,
          "pitch": 0.3035632374845161,
          "rotation": 0,
          "target": "1-hall_off-sala"
        }
      ],
      "infoHotspots": [
        {
          "yaw": 2.050591188250791,
          "pitch": 0.22052013799503278,
          "title": "<h1> &ensp; Body </h1>",
          "text": "<h2> <p>'What else can I do? There is no one here to give him a decent burial.' </p> <br> <p id='p1'> - Heather. </p> </h2>"
        },
        {
          "yaw": 1.3102031784939001,
          "pitch": -0.10113714895573445,
          "title": "<h1> &ensp; Photo </h1>",
          "text": "<h2> <img src='img/photo.jpg' class='center'><br><p> A photo of Harry and Heather. The image of Harry is just a render of him from the first game composed into one of Heather. Because of this, not only does Harry not appear to have aged in the photo, but the two of them are also the same height. It was most likely removed from the final version because of these inaccuracies. </p><br><p> The text attached to the picture in the game's source code reads: </p><br><p>  ‘It's of dad and me at Christmas. Looking at this makes me want to try even harder. I have to... I can't lose. They killed my dad and they have to pay for it.’ </p> <h2>"
        }
      ]
    },
    {
      "id": "41-harry_room_on-tv",
      "name": "Harry_room_on (tv)",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -2.243814240165742,
        "pitch": 0.25969568445479396,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 0.4346030661066358,
          "pitch": 0.33582870998764847,
          "rotation": 0,
          "target": "39-harry_bathroom_on"
        },
        {
          "yaw": -0.9215024599728441,
          "pitch": 0.2863451813868707,
          "rotation": 0,
          "target": "2-hall_on-sala"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "42-vazio_cozinha",
      "name": "vazio_cozinha",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "pitch": 0,
        "yaw": 0,
        "fov": 1.5707963267948966
      },
      "linkHotspots": [
        {
          "yaw": -1.2751945676933545,
          "pitch": 0.3300197459619767,
          "rotation": 0,
          "target": "43-vazio_hall_on"
        },
        {
          "yaw": 0,
          "pitch": 0,
          "rotation": 0,
          "target": "30-cozinha_off-4"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "43-vazio_hall_on",
      "name": "vazio_hall_on",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -3.063520311703437,
        "pitch": 0.09151241221041317,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -0.5325019466702692,
          "pitch": 0.26150510174947605,
          "rotation": 0,
          "target": "44-vazio_sala_on"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "44-vazio_sala_on",
      "name": "vazio_sala_on",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -0.5773006319992984,
        "pitch": 0.06249130125514313,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -1.8724097409489175,
          "pitch": 0.30882611299922225,
          "rotation": 0,
          "target": "45-vazio_varanda"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "45-vazio_varanda",
      "name": "vazio_varanda",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -3.05997803117158,
        "pitch": 0.23220884338402037,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -0.1514977309052803,
          "pitch": 0.32260607278421993,
          "rotation": 0,
          "target": "46-vazio_sala_off"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "46-vazio_sala_off",
      "name": "vazio_sala_off",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 1.3816355459326157,
        "pitch": -0.024085825383220794,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 2.416546655209233,
          "pitch": 0.2868346500752921,
          "rotation": 0,
          "target": "47-vazio_hall_off"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "47-vazio_hall_off",
      "name": "vazio_hall_off",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": 2.3896382742873925,
        "pitch": 0.1797878078891486,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": 2.7359217939774467,
          "pitch": 0.48174295505033093,
          "rotation": 0,
          "target": "48-vazio_door"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "48-vazio_door",
      "name": "vazio_door",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -0.0120807036278201,
        "pitch": 0.11762747433246368,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [
        {
          "yaw": -0.023207827188537422,
          "pitch": 0.07767347195349217,
          "rotation": 0,
          "target": "49-end"
        }
      ],
      "infoHotspots": []
    },
    {
      "id": "49-end",
      "name": "end",
      "levels": [
        {
          "tileSize": 256,
          "size": 256,
          "fallbackOnly": true
        },
        {
          "tileSize": 512,
          "size": 512
        }
      ],
      "faceSize": 500,
      "initialViewParameters": {
        "yaw": -0.0013474578372481005,
        "pitch": -1.4207648177001957,
        "fov": 1.4134061960355204
      },
      "linkHotspots": [],
      "infoHotspots": []
    }
  ],
  "name": "Silent Hill Tour",
  "settings": {
    "mouseViewMode": "drag",
    "autorotateEnabled": false,
    "fullscreenButton": true,
    "viewControlButtons": true
  }
};
